### ISSUE TITLE
Crashes when an Arduino Yun ic connected via Usb

### ISSUE THREAD

**Issue by rahulraj64** [androidthings/sample-usbenum#1]
The sample app crashes when an _Arduino Yun_ is connected to the _Raspberry Pi_ running _Android Things_. 

**Log**

FATAL EXCEPTION: main
    Process: com.example.androidthings.usbenum, PID: 7369
    java.lang.ArrayIndexOutOfBoundsException: length=64; index=64
    at com.example.androidthings.usbenum.ConfigurationDescriptor.parseResponse(ConfigurationDescriptor.java:125)
    at com.example.androidthings.usbenum.ConfigurationDescriptor.fromDeviceConnection(ConfigurationDescriptor.java:54)
    at com.example.androidthings.usbenum.UsbActivity.printDeviceDetails(UsbActivity.java:155)
    at com.example.androidthings.usbenum.UsbActivity.handleIntent(UsbActivity.java:96)
    at com.example.androidthings.usbenum.UsbActivity.onNewIntent(UsbActivity.java:61)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1223)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1235)
    at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2783)
    at android.app.ActivityThread.performNewIntents(ActivityThread.java:2795)
    at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2804)
    at android.app.ActivityThread.-wrap15(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1539)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6077)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by badarshahzad** [comment]
Hi @rahulraj64 , did you try arduino communication with raspberry? how did you do that could you share your experience and sample.

**Comment by rahulraj64** [comment]
Td43erfdreereeewseeeets
